### ISSUE TITLE
FormatException: Bad UTF-8 encoding 0x20 (at offset 40453)

### ISSUE THREAD

**Issue by hgouveia** [jg-l/metadata_fetch#10]
Hello, 

The package has some issue with some UTF-8 encoded pages,
this is the code: 
```dart
void main() async {
  String url = 'https://buff.ly/2CnEsKq';
  Metadata data = await extract(url);
  print(data.toMap());
  // output: {title: null, description: null, image: null, url: null}
}
```

after some debugging, I figure out that I was getting an error in the **catch** section in these lines
https://github.com/jg-l/metadata_fetch/blob/fc92fa9d5f6c70082b53c83a8f5630ee1a61a98a/lib/src/metadata_fetch_base.dart#L52-L57

and the error message is `FormatException: Bad UTF-8 encoding 0x20 (at offset 40453)`

**Comment by fayeed** [comment]
@hgouveia I think this is because you are using a link shortener & when you get the HTML of the site there's a trailing '%' sign at the end of the HTML which might be the issue, you might wanna start using the full link. I think this should be closed as this doesn't seem to be the issue with the package.

![image](https://user-images.githubusercontent.com/8464270/94142908-99f3f500-fe8c-11ea-93da-55423af4b0b8.png)
