### ISSUE TITLE
CORS issue on flutter web

### ISSUE THREAD

**Issue by dheerajsarwaiya** [jg-l/metadata_fetch#11]
is there a way to fix CORS issue on flutter web?

`Access to XMLHttpRequest at 'https://pub.dev/' from origin 'https://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by llucax** [comment]
Unfortunately I don't think there is a way around it, it's a browser security feature. I was also bitten by this and it seems the only way to deal with this is to add some proxy. I have trouble seeing how being able to fetch stuff using `XMLHttpRequest` is an issue but fetching stuff from the HTML itself is not. I guess it might be because one could use browsers to DoS any arbritrary site when used in a script while when in static HTML the effect is much more contained, but it is a very very annoying limitation indeed.

**Comment by jg-l** [comment]
Use a proxy for Cross Site requests (for flutter web)

**Comment by KurdAppDev** [comment]
if you are using chrome use this extension for enable CORS
https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en
