### ISSUE TITLE
OpenGraph returns null from YouTube link.

### ISSUE THREAD

**Issue by rindokim** [jg-l/metadata_fetch#16]
openGraph() doesn't recognize YouTube links.

**Comment by ivanchaukn** [comment]
I'm having the issue. Can anyone help?

**Comment by jrcodev** [comment]
I forked the package, and run a test with youtube link, the metadata was fetch with success, but in flutter tests, returns null.

**Comment by jrcodev** [comment]
I found that the version of pub.dev differs from the version of github. My temporary solution was fork this repository, and:

```
  metadata_fetch:
    git: git://github.com/jrcodev/metadata_fetch.git
```

I really wanted that the autor says a thing about the package. Seems abandoned. I really enjoy this package, because my app uses very metadata, and this is very useful for me. I am willing to collaborate in some way.

**Comment by jg-l** [comment]
It works on the latest version on pub 3.4

    var url = 'https://www.youtube.com/watch?v=JFm7YDVlqnI';
    var response = await http.get(url);
    var document = responseToDocument(response);

    var data = MetadataParser.parse(document);
    print(data);

    // Just Opengraph
    var og = MetadataParser.openGraph(document);
    print('OG $og');
    
    // OG {title: Drake - Laugh Now Cry Later (Official Music Video) ft. Lil Durk, description: Laugh Now Cry Later ft. Lil Durk available everywhere now: http://drake.lnk.to/lnclConnect with Drake:https://www.instagram.com/champagnepapi https://www.fac..., image: https://i.ytimg.com/vi/JFm7YDVlqnI/maxresdefault.jpg, url: https://www.youtube.com/watch?v=JFm7YDVlqnI}

**Comment by jrcodev** [comment]
This issue should be closed.
