### ISSUE TITLE
HttpRequestData extension uses a hidden global

### ISSUE THREAD

**Issue by llucax** [jg-l/metadata_fetch#19]
As shown by the test added in #17, using a global to fakely store the `requestUrl` in `Document` can have very nasty effects. Since the user of the library is the one really knowing where the data to parse is coming from, I don't think there is any need for having the extension at all.

**Comment by benPesso** [comment]
I agree. This extension should be removed.

I would also argue that the map extensions should be removed, as they might conflict with other extensions that a developer might have created. Shorthand isn't always the right approach.

**Comment by jg-l** [comment]
I will make some design changes

**Comment by jg-l** [comment]
Removed the extension that added `requestURL` in `Document`.

Following @llucax 's recommendation, the API user knows the URL of the document. However, the semantic URL provided by metadata schemas should not be ignored, and so that takes priority first. I believe only OpenGraph provides a standard url metadata in `og:url`.

In the case where no URLs are extracted by the parsers, the given URL to `MetadataFetch.extract(url)` will be used to fill in `Metadata.url` and also used to resolve images with relative URLs. 

For manual parsing, we can use `MetadataParser.parse(document, url: url)` to provide a fallback URL when none is found.
